export default {
    TAUNT_TOLERANCE: 2,
    LOCALSTORAGE_HIGHSCORE_KEY: "gundooz-highscore",
    LOCALSTORAGE_USERNAME_KEY: "gundooz-username",
    LOCALSTORAGE_EXISTINGUSERS_KEY: "gundooz-existingusers",
    RESTRICTED_KEYWORDS: ["null", "undefined"],
    CORRECT_SCORE: 10,
    MISSED_SCORE: -10,
    WRONGED_SCORE: -5,
    MAX_ALLOWED_USER_IN_DEVICE: 6,
    BASE_URL: "https://gundoosmean-server.herokuapp.com/",
    USERNAME_REGEX: "^[a-zA-Z0-9_-]$",
    TAUNT_TYPE: {
        CASUAL: "casual",
        GIVEUP: "giveup"
    },
    TAUNTS: [
        "Sigh. You don't even have to move from your couch to do this. Can't you do better?",
        "This is what happens when you use your brain as a stepney.",
        "Look. Penguins can't be vegan okay? Go feed my fish.",
        "Hey you're melting all my ice and now you're starving my fish ????",
        "Ooooh good job. If you were trying to disappoint.",
        "With memory like that, are you sure you remember your name?",
        "Yo brain so smoll, it's a floppy disk.",
        "Okay you really need to get your brain tested. This isn't normal.",
        "You should have stayed as apes -_-",
        "Twinkle Twinkle tiny brain, Why you give me so much pain?",
        "Are you trying to make snails feel fast?",
        "Your neurons fire like chilled water.",
        "I am sorry for your loss. Memory loss.",
        "Erm. Are you sure you know English? Feed. The. Fish.",
        "Thank you for participating in this experiment. We now know that humans are idiots.",
        "Are you crying yet? You should be.",
        "You can't hide the score you know? I'll know.",
        "Your brain is scrambled eggs -_-",
        "Obliviate! Is useless on you.",
        "It's not illegal for penguins to commit murder. Remember that.",
        "You bimbling bumbling babboon!",
        "Your bogart must be your brain. :)",
        "Are you Alice in Blunderland?",
        "I hope all your pizzas have pineapples.",
        "Row row row your boat, gently down the stream, and don't come back -_- ",
        "Hocus Pocus, YOU NEED TO FOCUS!",
        "And you say goldfish have the smallest memory span? Ahem. Ahem."
    ],
    GIVEUP_TAUNTS: [
        "I'll be even more menacing next time...",
        "Why don’t you rather give up on torturing us?",
        "Look who's heating up like the planet.",
        "Lost steam, have we?",
        "Ahem. Ahem. Giving up, are we?"
    ],
    CELL_FISH_STYLE_CLASSES: [
        "cell-fish-1",
        "cell-fish-2",
        "cell-fish-3",
        "cell-fish-4",
        "cell-fish-5",
        "cell-fish-6",
        "cell-fish-7"
    ]
}